"""
Preset themes for AOJ Command OS.
This module provides default theme configurations that can be loaded into the database.
"""

PRESET_THEMES = [
    {
        "name": "AOJ Tactical Dark",
        "is_active": True,
        "primary_color": "#0d150f",
        "secondary_color": "#2f4f3b",
        "accent_color": "#b6f784",
        "background_color": "#070a07",
        "panel_color": "#17241b",
        "text_color": "#edf9e8",
        "warning_color": "#ffc246",
        "danger_color": "#f36b6b",
        "success_color": "#4ade80",
        "font_family": "'Space Grotesk', sans-serif",
        "border_radius": "6px",
        "density": "normal",
        "background_style": "gradient",
        "logo_url": "/aoj-logo.png",
    },
    {
        "name": "High Contrast Outdoor",
        "is_active": False,
        "primary_color": "#000000",
        "secondary_color": "#ffffff",
        "accent_color": "#ffaa00",
        "background_color": "#1a1a1a",
        "panel_color": "#333333",
        "text_color": "#ffffff",
        "warning_color": "#ff6600",
        "danger_color": "#ff0000",
        "success_color": "#00ff00",
        "font_family": "'Arial', sans-serif",
        "border_radius": "2px",
        "density": "spacious",
        "background_style": "solid",
        "logo_url": "/logo-hc.png",
    },
    {
        "name": "Minimal Admin",
        "is_active": False,
        "primary_color": "#f5f5f5",
        "secondary_color": "#e0e0e0",
        "accent_color": "#2196f3",
        "background_color": "#fafafa",
        "panel_color": "#ffffff",
        "text_color": "#212121",
        "warning_color": "#ff9800",
        "danger_color": "#f44336",
        "success_color": "#4caf50",
        "font_family": "'Segoe UI', Tahoma, sans-serif",
        "border_radius": "4px",
        "density": "compact",
        "background_style": "solid",
        "logo_url": "/logo-minimal.png",
    },
    {
        "name": "Red Team Command",
        "is_active": False,
        "primary_color": "#1a0000",
        "secondary_color": "#4d0000",
        "accent_color": "#ff3333",
        "background_color": "#0d0000",
        "panel_color": "#330000",
        "text_color": "#ffcccc",
        "warning_color": "#ff6666",
        "danger_color": "#cc0000",
        "success_color": "#ff9999",
        "font_family": "'Space Grotesk', sans-serif",
        "border_radius": "6px",
        "density": "normal",
        "background_style": "gradient",
        "logo_url": "/logo-red.png",
    },
    {
        "name": "Blue Team Command",
        "is_active": False,
        "primary_color": "#000d1a",
        "secondary_color": "#002a4d",
        "accent_color": "#3399ff",
        "background_color": "#000633",
        "panel_color": "#003366",
        "text_color": "#ccddff",
        "warning_color": "#6699ff",
        "danger_color": "#0066cc",
        "success_color": "#99ccff",
        "font_family": "'Space Grotesk', sans-serif",
        "border_radius": "6px",
        "density": "normal",
        "background_style": "gradient",
        "logo_url": "/logo-blue.png",
    },
]
