"""Add props_needed to schedule_items

Revision ID: da4fc4d98c2c
Revises: 20260511_0001
Create Date: 2026-05-18 06:06:10.234286

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da4fc4d98c2c'
down_revision: Union[str, None] = '20260511_0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ai_conversations', 'status',
               existing_type=sa.TEXT(),
               server_default=None,
               type_=sa.String(length=30),
               existing_nullable=False)
    op.alter_column('ai_conversations', 'memory_summary',
               existing_type=sa.TEXT(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('ai_conversations', 'learned_trends',
               existing_type=sa.TEXT(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('ai_conversations', 'correction_memory',
               existing_type=sa.TEXT(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('ai_messages', 'confidence',
               existing_type=sa.REAL(),
               server_default=None,
               type_=sa.Float(),
               existing_nullable=False)
    op.alter_column('ai_messages', 'used_context',
               existing_type=sa.TEXT(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('ai_messages', 'suggested_actions',
               existing_type=sa.TEXT(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('ai_messages', 'blocked_actions',
               existing_type=sa.TEXT(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('ai_messages', 'warnings',
               existing_type=sa.TEXT(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('ai_messages', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.create_index(op.f('ix_ai_messages_action_request_id'), 'ai_messages', ['action_request_id'], unique=False)
    op.create_foreign_key(None, 'ai_messages', 'ai_action_requests', ['action_request_id'], ['id'])
    op.alter_column('custom_game_modes', 'team_setup_json',
               existing_type=sa.TEXT(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('custom_game_modes', 'objectives_json',
               existing_type=sa.TEXT(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('custom_game_modes', 'win_conditions_json',
               existing_type=sa.TEXT(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('custom_game_modes', 'required_props_json',
               existing_type=sa.TEXT(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('custom_game_modes', 'briefing_text',
               existing_type=sa.TEXT(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('custom_game_modes', 'marshal_notes',
               existing_type=sa.TEXT(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('devices', 'device_id',
               existing_type=sa.TEXT(),
               type_=sa.String(length=64),
               nullable=False)
    op.alter_column('devices', 'ip_address',
               existing_type=sa.VARCHAR(length=45),
               nullable=True)
    op.alter_column('devices', 'battery_level',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('devices', 'signal_strength',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('devices', 'firmware_version',
               existing_type=sa.TEXT(),
               server_default=None,
               type_=sa.String(length=50),
               existing_nullable=False)
    op.alter_column('devices', 'location',
               existing_type=sa.TEXT(),
               server_default=None,
               type_=sa.String(length=140),
               existing_nullable=False)
    op.alter_column('devices', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.create_index(op.f('ix_devices_device_id'), 'devices', ['device_id'], unique=True)
    op.create_foreign_key(None, 'devices', 'device_types', ['device_type_id'], ['id'])
    op.drop_column('devices', 'device_type')
    op.alter_column('game_sessions', 'main_timer_seconds',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('game_sessions', 'phase_timer_seconds',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('game_sessions', 'red_score',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('game_sessions', 'blue_score',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('game_sessions', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.alter_column('game_sessions', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.create_foreign_key(None, 'game_sessions', 'game_modes', ['game_mode_id'], ['id'])
    op.alter_column('missions', 'status',
               existing_type=sa.VARCHAR(length=8),
               type_=sa.Enum('planned', 'active', 'complete', 'cancelled', name='missionstatus'),
               existing_nullable=False)
    op.alter_column('missions', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.create_foreign_key(None, 'missions', 'users', ['created_by_id'], ['id'])
    op.create_foreign_key(None, 'missions', 'game_modes', ['game_mode_id'], ['id'])
    op.alter_column('props', 'auth_token_hash',
               existing_type=sa.TEXT(),
               server_default=None,
               type_=sa.String(length=128),
               existing_nullable=False)
    op.add_column('schedule_items', sa.Column('props_needed', sa.Text(), nullable=False))
    op.alter_column('schedule_items', 'game_mode',
               existing_type=sa.TEXT(),
               server_default=None,
               type_=sa.String(length=120),
               existing_nullable=False)
    op.alter_column('schedule_items', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.alter_column('schedule_items', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.create_foreign_key(None, 'schedule_items', 'game_sessions', ['game_session_id'], ['id'])
    op.add_column('score_events', sa.Column('player_id', sa.Integer(), nullable=True))
    op.add_column('score_events', sa.Column('reason', sa.String(length=255), nullable=False))
    op.add_column('score_events', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.alter_column('score_events', 'team_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_foreign_key(None, 'score_events', 'players', ['player_id'], ['id'])
    op.create_foreign_key(None, 'system_logs', 'devices', ['device_id'], ['id'])
    op.create_foreign_key(None, 'system_logs', 'game_sessions', ['game_session_id'], ['id'])
    op.create_foreign_key(None, 'system_logs', 'missions', ['mission_id'], ['id'])
    op.create_foreign_key(None, 'system_logs', 'users', ['user_id'], ['id'])
    op.add_column('teams', sa.Column('side', sa.Enum('red', 'blue', 'neutral', 'custom', name='teamside'), nullable=False))
    op.add_column('teams', sa.Column('score', sa.Integer(), nullable=False))
    op.add_column('teams', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('teams', sa.Column('updated_at', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('teams', 'updated_at')
    op.drop_column('teams', 'created_at')
    op.drop_column('teams', 'score')
    op.drop_column('teams', 'side')
    op.drop_constraint(None, 'system_logs', type_='foreignkey')
    op.drop_constraint(None, 'system_logs', type_='foreignkey')
    op.drop_constraint(None, 'system_logs', type_='foreignkey')
    op.drop_constraint(None, 'system_logs', type_='foreignkey')
    op.drop_constraint(None, 'score_events', type_='foreignkey')
    op.alter_column('score_events', 'team_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('score_events', 'created_at')
    op.drop_column('score_events', 'reason')
    op.drop_column('score_events', 'player_id')
    op.drop_constraint(None, 'schedule_items', type_='foreignkey')
    op.alter_column('schedule_items', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.alter_column('schedule_items', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.alter_column('schedule_items', 'game_mode',
               existing_type=sa.String(length=120),
               server_default=sa.text("('')"),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_column('schedule_items', 'props_needed')
    op.alter_column('props', 'auth_token_hash',
               existing_type=sa.String(length=128),
               server_default=sa.text("('')"),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_constraint(None, 'missions', type_='foreignkey')
    op.drop_constraint(None, 'missions', type_='foreignkey')
    op.alter_column('missions', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.alter_column('missions', 'status',
               existing_type=sa.Enum('planned', 'active', 'complete', 'cancelled', name='missionstatus'),
               type_=sa.VARCHAR(length=8),
               existing_nullable=False)
    op.drop_constraint(None, 'game_sessions', type_='foreignkey')
    op.alter_column('game_sessions', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.alter_column('game_sessions', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.alter_column('game_sessions', 'blue_score',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('game_sessions', 'red_score',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('game_sessions', 'phase_timer_seconds',
               existing_type=sa.INTEGER(),
               server_default=sa.text('(300)'),
               existing_nullable=False)
    op.alter_column('game_sessions', 'main_timer_seconds',
               existing_type=sa.INTEGER(),
               server_default=sa.text('(1800)'),
               existing_nullable=False)
    op.add_column('devices', sa.Column('device_type', sa.VARCHAR(length=50), nullable=False))
    op.drop_constraint(None, 'devices', type_='foreignkey')
    op.drop_index(op.f('ix_devices_device_id'), table_name='devices')
    op.alter_column('devices', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.alter_column('devices', 'location',
               existing_type=sa.String(length=140),
               server_default=sa.text("('')"),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('devices', 'firmware_version',
               existing_type=sa.String(length=50),
               server_default=sa.text("('')"),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('devices', 'signal_strength',
               existing_type=sa.INTEGER(),
               server_default=sa.text('(100)'),
               existing_nullable=False)
    op.alter_column('devices', 'battery_level',
               existing_type=sa.INTEGER(),
               server_default=sa.text('(100)'),
               existing_nullable=False)
    op.alter_column('devices', 'ip_address',
               existing_type=sa.VARCHAR(length=45),
               nullable=False)
    op.alter_column('devices', 'device_id',
               existing_type=sa.String(length=64),
               type_=sa.TEXT(),
               nullable=True)
    op.alter_column('custom_game_modes', 'marshal_notes',
               existing_type=sa.TEXT(),
               server_default=sa.text("('')"),
               existing_nullable=False)
    op.alter_column('custom_game_modes', 'briefing_text',
               existing_type=sa.TEXT(),
               server_default=sa.text("('')"),
               existing_nullable=False)
    op.alter_column('custom_game_modes', 'required_props_json',
               existing_type=sa.TEXT(),
               server_default=sa.text("'[]'"),
               existing_nullable=False)
    op.alter_column('custom_game_modes', 'win_conditions_json',
               existing_type=sa.TEXT(),
               server_default=sa.text("'[]'"),
               existing_nullable=False)
    op.alter_column('custom_game_modes', 'objectives_json',
               existing_type=sa.TEXT(),
               server_default=sa.text("'[]'"),
               existing_nullable=False)
    op.alter_column('custom_game_modes', 'team_setup_json',
               existing_type=sa.TEXT(),
               server_default=sa.text("'{}'"),
               existing_nullable=False)
    op.drop_constraint(None, 'ai_messages', type_='foreignkey')
    op.drop_index(op.f('ix_ai_messages_action_request_id'), table_name='ai_messages')
    op.alter_column('ai_messages', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.alter_column('ai_messages', 'warnings',
               existing_type=sa.TEXT(),
               server_default=sa.text("'[]'"),
               existing_nullable=False)
    op.alter_column('ai_messages', 'blocked_actions',
               existing_type=sa.TEXT(),
               server_default=sa.text("'[]'"),
               existing_nullable=False)
    op.alter_column('ai_messages', 'suggested_actions',
               existing_type=sa.TEXT(),
               server_default=sa.text("'[]'"),
               existing_nullable=False)
    op.alter_column('ai_messages', 'used_context',
               existing_type=sa.TEXT(),
               server_default=sa.text("'[]'"),
               existing_nullable=False)
    op.alter_column('ai_messages', 'confidence',
               existing_type=sa.Float(),
               server_default=sa.text('(0.0)'),
               type_=sa.REAL(),
               existing_nullable=False)
    op.alter_column('ai_conversations', 'correction_memory',
               existing_type=sa.TEXT(),
               server_default=sa.text("'{}'"),
               existing_nullable=False)
    op.alter_column('ai_conversations', 'learned_trends',
               existing_type=sa.TEXT(),
               server_default=sa.text("'[]'"),
               existing_nullable=False)
    op.alter_column('ai_conversations', 'memory_summary',
               existing_type=sa.TEXT(),
               server_default=sa.text("('')"),
               existing_nullable=False)
    op.alter_column('ai_conversations', 'status',
               existing_type=sa.String(length=30),
               server_default=sa.text("'active'"),
               type_=sa.TEXT(),
               existing_nullable=False)
    # ### end Alembic commands ###
