"""Schemas package – re-exports every Pydantic schema for backward-compatible
``from app.schemas import X`` and ``from app import schemas`` usage."""

from app.schemas.ai import (
    AIActionRequestRead,
    AIAskRequest,
    AIAskResponse,
    AIChatReplyResponse,
    AIConversationClearResponse,
    AIConversationCreateRequest,
    AIConversationRead,
    AIMessageCreateRequest,
    AIMessageRead,
    AIResponsePayload,
)
from app.schemas.announcement_rule import (
    AnnouncementRuleBase,
    AnnouncementRuleCreate,
    AnnouncementRuleRead,
    AnnouncementRuleUpdate,
)
from app.schemas.christy_announcement import (
    ChristyAnnouncementBase,
    ChristyAnnouncementCreate,
    ChristyAnnouncementRead,
)
from app.schemas.customization import (
    AIAssistantSettingsBase,
    AIAssistantSettingsRead,
    AIAssistantSettingsUpdate,
    ActiveThemeSetRequest,
    CustomGameModeBase,
    CustomGameModeCreate,
    CustomGameModeRead,
    CustomGameModeUpdate,
    CustomKnowledgeEntryBase,
    CustomKnowledgeEntryCreate,
    CustomKnowledgeEntryRead,
    CustomKnowledgeEntryUpdate,
    CustomTeamBase,
    CustomTeamCreate,
    CustomTeamRead,
    CustomTeamUpdate,
    VisualThemeBase,
    VisualThemeCreate,
    VisualThemeRead,
    VisualThemeUpdate,
)
from app.schemas.game_event import GameEventBase, GameEventCreate, GameEventRead
from app.schemas.game_mode import GameModeBase, GameModeCreate, GameModeRead, GameModeUpdate
from app.schemas.device import DeviceBase, DeviceCreate, DeviceRead
from app.schemas.game_result import (
    GameResultBase,
    GameResultCreate,
    GameResultRead,
    ResultsResetDayRequest,
    ResultsResetDayResponse,
    ResultsSummaryResponse,
)
from app.schemas.game_session import GameSessionBase, GameSessionCreate, GameSessionRead, GameSessionUpdate
from app.schemas.mission import MissionBase, MissionCreate, MissionRead, MissionUpdate
from app.schemas.health import HealthResponse
from app.schemas.mission import MissionBase, MissionCreate, MissionRead
from app.schemas.mission_control import (
    MissionControlCreateMissionRequest,
    MissionControlObjective,
    MissionControlObjectiveStatusRequest,
    MissionControlScoreRequest,
    MissionControlStateResponse,
    TeamReadyRequest,
)
from app.schemas.prop import (
    PropBase,
    PropCommandRequest,
    PropCreate,
    PropRead,
    PropStatusReport,
    PropUpdate,
)
from app.schemas.player_squad import (
    PlayerTeamAssignmentBase,
    PlayerTeamAssignmentCreate,
    PlayerTeamAssignmentRead,
    SquadBase,
    SquadCreate,
    SquadMemberBase,
    SquadMemberCreate,
    SquadMemberRead,
    SquadRead,
    SquadUpdate,
)
from app.schemas.schedule import (
    ScheduleItemBase,
    ScheduleItemCreate,
    ScheduleItemRead,
    ScheduleItemUpdate,
    ScheduleOverviewResponse,
)
from app.schemas.score_event import ScoreEventBase, ScoreEventCreate, ScoreEventRead
from app.schemas.system import SystemStatusResponse, SystemSettingCreate, SystemSettingRead, SystemSettingUpdate
from app.schemas.system_log import SystemLogBase, SystemLogCreate, SystemLogRead
from app.schemas.team import TeamBase, TeamCreate, TeamRead
from app.schemas.update_center import (
    FirmwareApplyRequest,
    FirmwareApplyResponse,
    FirmwarePackageRead,
    FirmwareRolloutJobRead,
    FirmwareRolloutProgressUpdateRequest,
    FirmwareRolloutTargetRead,
    UpdateCenterActionResponse,
    UpdateCenterStatusResponse,
    UpdatePackagePlaceholderRequest,
)
from app.schemas.user_role import UserRoleBase, UserRoleCreate, UserRoleRead

__all__ = [
    "AIActionRequestRead",
    "AIAskRequest",
    "AIAskResponse",
    "AIChatReplyResponse",
    "AIConversationClearResponse",
    "AIConversationCreateRequest",
    "AIConversationRead",
    "AIMessageCreateRequest",
    "AIMessageRead",
    "AIResponsePayload",
    "AIAssistantSettingsBase",
    "AIAssistantSettingsRead",
    "AIAssistantSettingsUpdate",
    "ActiveThemeSetRequest",
    "AnnouncementRuleBase",
    "AnnouncementRuleCreate",
    "AnnouncementRuleRead",
    "AnnouncementRuleUpdate",
    "ChristyAnnouncementBase",
    "ChristyAnnouncementCreate",
    "ChristyAnnouncementRead",
    "CustomGameModeBase",
    "CustomGameModeCreate",
    "CustomGameModeRead",
    "CustomGameModeUpdate",
    "CustomKnowledgeEntryBase",
    "CustomKnowledgeEntryCreate",
    "CustomKnowledgeEntryRead",
    "CustomKnowledgeEntryUpdate",
    "CustomTeamBase",
    "CustomTeamCreate",
    "CustomTeamRead",
    "CustomTeamUpdate",
    "VisualThemeBase",
    "VisualThemeCreate",
    "VisualThemeRead",
    "VisualThemeUpdate",
    "DeviceBase",
    "DeviceCreate",
    "DeviceRead",
    "GameEventBase",
    "GameEventCreate",
    "GameEventRead",
    "GameModeBase",
    "GameModeCreate",
    "GameModeRead",
    "GameModeUpdate",
    "GameResultBase",
    "GameResultCreate",
    "GameResultRead",
    "ResultsResetDayRequest",
    "ResultsResetDayResponse",
    "ResultsSummaryResponse",
    "GameSessionBase",
    "GameSessionCreate",
    "GameSessionRead",
    "GameSessionUpdate",
    "HealthResponse",
    "MissionBase",
    "MissionCreate",
    "MissionRead",
    "MissionUpdate",
    "MissionControlCreateMissionRequest",
    "MissionControlObjective",
    "MissionControlObjectiveStatusRequest",
    "MissionControlScoreRequest",
    "MissionControlStateResponse",
    "TeamReadyRequest",
    "PropBase",
    "PropCommandRequest",
    "PropCreate",
    "PropRead",
    "PropStatusReport",
    "PropUpdate",
    "PlayerTeamAssignmentBase",
    "PlayerTeamAssignmentCreate",
    "PlayerTeamAssignmentRead",
    "ScheduleItemBase",
    "ScheduleItemCreate",
    "ScheduleItemRead",
    "ScheduleItemUpdate",
    "ScheduleOverviewResponse",
    "ScoreEventBase",
    "ScoreEventCreate",
    "ScoreEventRead",
    "SystemStatusResponse",
    "SystemSettingCreate",
    "SystemSettingRead",
    "SystemSettingUpdate",
    "SystemLogBase",
    "SystemLogCreate",
    "SystemLogRead",
    "SquadBase",
    "SquadCreate",
    "SquadMemberBase",
    "SquadMemberCreate",
    "SquadMemberRead",
    "SquadRead",
    "SquadUpdate",
    "TeamBase",
    "TeamCreate",
    "TeamRead",
    "FirmwareApplyRequest",
    "FirmwareApplyResponse",
    "FirmwarePackageRead",
    "FirmwareRolloutJobRead",
    "FirmwareRolloutProgressUpdateRequest",
    "FirmwareRolloutTargetRead",
    "UpdateCenterActionResponse",
    "UpdateCenterStatusResponse",
    "UpdatePackagePlaceholderRequest",
    "UserRoleBase",
    "UserRoleCreate",
    "UserRoleRead",
]
